// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm7FqfvXkOVB0nglTUw7g6_5zX0cfCeDQ',
    appId: '1:196505224409:web:f738496342f95f1762aac8',
    messagingSenderId: '196505224409',
    projectId: 'planit-croatia',
    authDomain: 'planit-croatia.firebaseapp.com',
    storageBucket: 'planit-croatia.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9KHJMJ3F0NwLX9NQDMET29BoEoSWkY9U',
    appId: '1:196505224409:android:7a349497d8e64de262aac8',
    messagingSenderId: '196505224409',
    projectId: 'planit-croatia',
    storageBucket: 'planit-croatia.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN90w4XzMruvB7xWJUv8fNhWsiWAlDyA8',
    appId: '1:196505224409:ios:f74f7cd5b7749af062aac8',
    messagingSenderId: '196505224409',
    projectId: 'planit-croatia',
    storageBucket: 'planit-croatia.appspot.com',
    iosBundleId: 'com.example.flutterproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN90w4XzMruvB7xWJUv8fNhWsiWAlDyA8',
    appId: '1:196505224409:ios:55f95b25a087215d62aac8',
    messagingSenderId: '196505224409',
    projectId: 'planit-croatia',
    storageBucket: 'planit-croatia.appspot.com',
    iosBundleId: 'com.example.flutterproject.RunnerTests',
  );
}
